import { TaskStatus } from "../components/Column/types";

export const TASKS = [
  {
    id: "a1b2c3d4-e5f6-7890-abcd-1234567890ef",
    title: "Build UI for onboarding flow",
    description: "Create the user interface for the onboarding process",
    status: TaskStatus.InProgress,
    created_at: new Date().toDateString(),
  },
  {
    id: "b2c3d4e5-f6g7-8910-bcde-2345678901fg",
    title: "Implement authentication system",
    description: "Develop the backend authentication logic",
    status: TaskStatus.ToDo,
    created_at: new Date().toDateString(),
  },
  {
    id: "c3d4e5f6-g7h8-9011-cdef-3456789012gh",
    title: "Set up database schema",
    description: "Design and implement the database structure",
    status: TaskStatus.Done,
    created_at: new Date().toDateString(),
  },
  {
    id: "d4e5f6g7-h8i9-0123-def0-4567890123hi",
    title: "Create landing page",
    description: "Develop a responsive landing page for the application",
    status: TaskStatus.InProgress,
    created_at: new Date().toDateString(),
  },
  {
    id: "e5f6g7h8-i9j0-1234-ef01-5678901234ij",
    title: "Optimize performance",
    description: "Improve the app's loading time and performance",
    status: TaskStatus.ToDo,
    created_at: new Date().toDateString(),
  },
  {
    id: "f6g7h8i9-j0k1-2345-f012-6789012345jk",
    title: "Fix login issues",
    description: "Resolve bugs related to user login functionality",
    status: TaskStatus.Done,
    created_at: new Date().toDateString(),
  },
  {
    id: "g7h8i9j0-k1l2-3456-0123-7890123456kl",
    title: "Test payment gateway integration",
    description: "Ensure that payment processing is functioning correctly",
    status: TaskStatus.InProgress,
    created_at: new Date().toDateString(),
  },
  {
    id: "h8i9j0k1-l2m3-4567-1234-8901234567lm",
    title: "Write unit tests",
    description: "Add unit tests to critical backend features",
    status: TaskStatus.ToDo,
    created_at: new Date().toDateString(),
  },
  {
    id: "i9j0k1l2-m3n4-5678-2345-9012345678mn",
    title: "Design email templates",
    description: "Create email templates for automated notifications",
    status: TaskStatus.Done,
    created_at: new Date().toDateString(),
  },
  {
    id: "j0k1l2m3-n4o5-6789-3456-0123456789no",
    title: "Set up CI/CD pipeline",
    description: "Automate the deployment process using CI/CD tools",
    status: TaskStatus.InProgress,
    created_at: new Date().toDateString(),
  },
  {
    id: "k1l2m3n4-o5p6-7890-4567-1234567890op",
    title: "Create user profile page",
    description: "Build a page for users to view and edit their profiles",
    status: TaskStatus.ToDo,
    created_at: new Date().toDateString(),
  },
  {
    id: "l2m3n4o5-p6q7-8901-5678-2345678901pq",
    title: "Implement push notifications",
    description: "Add real-time push notifications for important events",
    status: TaskStatus.Done,
    created_at: new Date().toDateString(),
  },
  {
    id: "m3n4o5p6-q7r8-9012-6789-3456789012qr",
    title: "Configure API rate limiting",
    description: "Set up rate limiting to protect the API from abuse",
    status: TaskStatus.InProgress,
    created_at: new Date().toDateString(),
  },
];
